### ISSUE TITLE
Brands are missing from typeahead

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-tag-facets-api#21]
E.g. Lex

I think this is because it's not listed as a taxonomy:-
https://github.com/Financial-Times/next-tag-facets-api/blob/b3e71ce7c245d9060d5e3a91824043d954f42394/server/controllers/search-controller.js#L12-L18

cc @andygout @mmockett

**Comment by i-like-robots** [comment]
Since we have purged all the [bad tags](https://github.com/Financial-Times/next-es-interface/issues/387) this filter may not be necessary at all.

However, for consideration is that this API currently powers some [trending tags functionality on stream pages](https://github.com/Financial-Times/next-stream-page/blob/f78079cabdb705199badf410b78b9b14a733186a/server/transforms/related-tags.js) in which we don't want brands to appear.

It came up earlier today that it may be useful to add taxonomies as an optional parameter, though I'd personally favour removing the taxonomy filter altogether.

**Comment by matthew-andrews** [comment]
so i think you're suggesting…  defaulting to all taxonomies, allow option of limiting taxonomies (for trending topics on stream pages)?

**Comment by i-like-robots** [comment]
I think there are two options (looking at the query gymnastics required I consider them exclusive):

1. Remove the taxonomy filter and don't worry about limiting taxonomies 
2. Maintain the current taxonomy filter but add a parameter to provide a replacement list of taxonomies

**Comment by i-like-robots** [comment]
Perhaps there is an option 3 (if I can figure it out) and that is having a match all taxonomy filter (bit of a contradiction!) with the option to provide a list to filter by.

**Comment by andygout** [comment]
Stating the obvious but if it's a toss-up between 2 and 3 then seems whichever is the shorter list (replacement list or filter list) would be the better bet.

**Comment by i-like-robots** [comment]
I think there is only one thing stopping us from going with option 1 or 2 and that is the `mediaType` taxonomy... can we purge this one too @matthew-andrews ?

**Comment by matthew-andrews** [comment]
do it

**Comment by i-like-robots** [comment]
https://github.com/Financial-Times/next-es-interface/pull/427

**Comment by i-like-robots** [comment]
So the plan of action is:

- Give ES interface a couple of days to filter out some of the mediaType tags from our index
- Update tag facets to not exclude any taxonomies by default
- Add a new taxonomies parameter to tag facets

**Comment by i-like-robots** [comment]
https://github.com/Financial-Times/next-tag-facets-api/pull/22
