### ISSUE TITLE
Readme misleading: `tagged` _excludes_ tags

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/next-tag-facets-api#33]
https://github.com/Financial-Times/next-tag-facets-api#reduce-content-tagged-with-the-given-tme-ids should be reconciled with https://github.com/Financial-Times/next-tag-facets-api/blob/master/server/queries/search-query.js#L39-L44 - they are opposites. Are tags in `tagged` supposed to be included or excluded?

**Comment by i-like-robots** [comment]
I know the conversation about this has long gone (as has @georgecrawford) but to clarify:

The `tagged` parameter will search for articles _tagged_ with those provided. The _exclude_ portion of the query will filter these tags from the aggregations - otherwise they'd simply be the top results and drill-down search (as used to be implemented on the original FastFT stream shown below) would not be possible.

![popstate](https://cloud.githubusercontent.com/assets/271645/22979040/e8fc3cca-f38c-11e6-9604-e09af358b4cd.gif)
